try {
  // აქ წერია ისეთი კოდი, რომელიც შეიძლება შეცდომას იწვევდეს
  // თუ კოდში შეცდომა მოხდა, ეს შეცდომა ავტომატურად გადავა catch ბლოკში
} catch (error) {
  // აქ ხდება შეცდომის დამუშავება
  // მაგალითად, ერორის მესიჯის გამოტანა ან fallback ფუნქციონალის გაშვება
}
